---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: dev
  labels:
    env: control 
spec:
  limits:
  - default:
      cpu: 1
    defaultRequest:
      cpu: "0.5"
    type: Container
